### ISSUE TITLE
Low Contrast in assignment table (Guest user)

### ISSUE THREAD

**Issue by Girl-C0d3** [jamieTardi/wow-rosters#12]
View/edit assignments page functions as expected however the contrast between the text and background when the assignment is displayed is very low as shown in attached image.

![Assignments_table](https://user-images.githubusercontent.com/64501770/137472890-6376b54f-706e-4fbc-bfb2-062189be0f01.PNG)

**Comment by jamieTardi** [comment]
font colours now correctly match the mode the user is in.
