### ISSUE TITLE
First name field accepts numbers and symbols as input

### ISSUE THREAD

**Issue by Girl-C0d3** [jamieTardi/wow-rosters#14]
Steps to recreate bug:
1. From the sign in portal click the button to sign up
2. Enter invalid input in the 'First Name' field - e.g. 123!. No error message is displayed to inform user this is not valid input for this field.
3. Fill in other input fields with a valid username, email address, password and repeated password.
4. Click sign up to create an account
Expected result: Account would not be created and there would be some form of error message displayed to indicate to the user that they must add a valid first name. 
Actual result: Account created.

Suggestion: Input field should only accept uppercase and lowercase characters.

![invalidFirstName](https://user-images.githubusercontent.com/64501770/137508382-94f01370-4246-45b7-8be0-fb0582804d4a.PNG)

**Comment by jamieTardi** [comment]
First name field now does not accept special characters. User is unable to continue account creation if this field has special character
<img width="396" alt="Screenshot 2021-10-16 at 16 00 28" src="https://user-images.githubusercontent.com/66372574/137592311-4945244f-ceda-46f8-b6a2-817c2fd0a17c.png">
s.
