### ISSUE TITLE
Password visible in 'Repeat password' field

### ISSUE THREAD

**Issue by Girl-C0d3** [jamieTardi/wow-rosters#9]
User navigates to the sign up form and fills in their information. 
When the user reaches the 'Password field' the password is hidden by default and the user can reveal the password by selecting the icon within the field. When the user confirms their password in the 'Repeat Password' field the password is shown in clear text and there is no icon to hide users input which is a security issue.
![bug1](https://user-images.githubusercontent.com/64501770/137364167-0da355a4-2b3c-4c8d-b1a5-27cfa76ab0f2.PNG)

**Comment by jamieTardi** [comment]
password no longer visible
